services:
  backend:
    build:
      context: safe-browsing-backend
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${SERVICE_USER_MONGODB}:${SERVICE_PASSWORD_MONGODB}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    expose: 
      - '8080'
  mongodb:
    image: mongo:7
    volumes:
      - threat-intel-backend-drive:/data/db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${SERVICE_USER_MONGODB}
      - MONGO_INITDB_ROOT_PASSWORD=${SERVICE_PASSWORD_MONGODB}
      - MONGO_INITDB_DATABASE
    