services:
  backend:
    build:
      context: safe-browsing-backend
    environment:
      - MONGODB_URI=mongodb://${SERVICE_USER_MONGODB}:${SERVICE_PASSWORD_MONGODB}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    expose: 
      - '8080'
  mongodb:
    image: mongo:7
    environment: 
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    